service:
  type: ClusterIP

namespace: "roboshop"

deployment:
  enabled: false

statefulset:
  enabled: false


image:
  repository: crysis307
  tag: latest

redis:
  enabled: false

mysql:
  enabled: false

schema:
  enabled: false


