apiVersion: v1
kind: Service
metadata:
    {{- include "robo.metadata" . | indent 4 }}
spec:
    type: {{ .Values.service.type }}
    selector:
      app: {{ .Value.component_name }}
    ports:
      {{- include "robo.service.ports" . | indent 6 }}

