# precona/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - main.yaml
  - pdb.yaml
  - seed-job.yaml
#  - servicemonitor.yaml
  - user-external-secret.yaml
  - storageclass.yaml
  # (add other YAMLs if you want)

# ðŸ‘‡ this is the key part
images:
  - name: crysis307/mongodb
    newTag: latest
